* SAMstrt

Recent studies revealed total transcript numbers per cell vary by cell
type and the condition. Therefore, many statistical tests for
differential expression are not necessarily applicable, since it
assumed that many genes are not differentially expressed. One solution
is addition of a same amount of spike-in control RNA molecules into
each sample, for example [Islam2011], and this SAMstrt package
provides the significance analysis of sequencing data with spike-in
normalization. The statistical backgrounds and the benefits depend on
SAMseq of the samr package [Li2011].

** Acknowledgements

Development of this package was supported by the Karolinska Institutet
Distinguished Professor Award to Juha Kere, and the Strategic Research
Area Grant for Diabetes to Karolinska Institutet. The computations
were performed on resources provided by SNIC through Uppsala
Multidisciplinary Center for Advanced Computational Science (UPPMAX)
under Project b2010037.

** References

- Islam S, et al. Characterization of the single-cell transcriptional landscape by highly multiplex RNA-seq. /Genome Res./ 2011 Jun 1.

- Katayama,S. et al. SAMstrt: Statistical test for differential
  expression in single-cell transcriptome with spike-in
  normalization. Submitted.

- Li,J. and Tibshirani,R. (2011) Finding consistent patterns: A
  nonparametric approach for identifying differential expression in
  RNA-Seq data. /Stat Methods Med Res./ Nov. 28, 2011.
